Fix workflow

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -85,8 +85,9 @@ jobs:
 
           # Extract the current tag and its SHA
           current_tag=${GITHUB_REF#refs/tags/}
-          current_sha=$(git rev-list -1 "${current_tag}")
-
+          echo "Current tag: ${current_tag}
+          current_sha=$(git rev-list -1 "${current_tag}") || echo "invalid"
+          echo "Current sha: ${current_sha}"
           # Count occurrences of the current SHA in the weekly SHA list
           n=$(echo "${weekly_sha}" | grep -c "${current_sha}")
           echo "Current tag ${current_tag} (${current_sha}) SHA found ${n} time(s)"
